[package]
name = "payjoin_ffi"
version = "0.20.0"
license = "MIT OR Apache-2.0"
edition = "2021"
exclude = ["tests"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "payjoin_ffi"

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.28.0", features = ["bindgen-tests"] }
bdk = { version = "0.29.0", features = ["all-keys", "use-esplora-ureq", "keys-bip39", "rpc"] }
#bitcoin-ffi = { git = "https://github.com/bitcoindevkit/bitcoin-ffi" }
bitcoind = { version = "0.36.0", features = ["0_21_2"] }
bitcoincore-rpc = "0.19.0"
http = "1"
payjoin-directory = { git = "https://github.com/payjoin/rust-payjoin", rev = "ef2ce55a57fe5270bc761bfcda58024ae45a93aa", features = ["danger-local-https"] }
ohttp-relay = "0.0.8"
rcgen = { version = "0.11" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
rustls = "0.22.2"
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.1.3", features = ["redis"] }
tokio = { version = "1.12.0", features = ["full"] }
[dependencies]

payjoin = { git = "https://github.com/payjoin/rust-payjoin", rev = "ef2ce55a57fe5270bc761bfcda58024ae45a93aa", features = ["send", "receive", "base64", "v2", "io"] }
uniffi = { version = "0.28.0", optional = true }
thiserror = "1.0.47"
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
url = "2.5.0"
base64 = "0.22.1"
hex = "0.4.3"


[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true


[features]
uniffi = ["uniffi/cli"]
danger-local-https = ["payjoin/danger-local-https"]
